//
//  PageLink.swift
//  Bubbles
//
//  Created by Martin Pilkington on 28/10/2019.
//  Copyright © 2019 M Cubed Software. All rights reserved.
//

import Cocoa

struct PageLink {
    static let host = "page"
    static let querySourceName = "source"
    static let queryAutoName = "auto"
    let destination: ModelID
    let source: ModelID?
    let autoGenerated: Bool

    init(destination: ModelID, source: ModelID? = nil, autoGenerated: Bool = false) {
        self.destination = destination
        self.source = source
        self.autoGenerated = autoGenerated
    }

    init?(url: URL) {
        guard let urlComponents = URLComponents(url: url, resolvingAgainstBaseURL: false),
            urlComponents.scheme == GlobalConstants.urlScheme,
            urlComponents.host == PageLink.host else {
            return nil
        }

        let path = urlComponents.path
        let destinationUUIDString = String(path[(path.index(after: path.startIndex))...])
        guard let destinationID = Page.modelID(withUUIDString: destinationUUIDString) else {
            return nil
        }

        var sourceID: ModelID? = nil
        var autoGenerated = false
        if let queryItems = urlComponents.queryItems?.indexed(by: \.name) {
            if let value = queryItems[PageLink.querySourceName]?.value {
                sourceID = Page.modelID(withUUIDString: value)
            }
            if let value = queryItems[PageLink.queryAutoName]?.value {
                autoGenerated = (value == "1")
            }
        }

        self.init(destination: destinationID, source: sourceID, autoGenerated: autoGenerated)
    }

    var url: URL {
        var urlComponents = URLComponents()
        urlComponents.scheme = GlobalConstants.urlScheme
        urlComponents.host = PageLink.host
        urlComponents.path = "/\(self.destination.uuid.uuidString)"
        var queryItems = [URLQueryItem]()
        if let source = self.source {
            queryItems.append(URLQueryItem(name: PageLink.querySourceName, value: source.uuid.uuidString))
        }
        if self.autoGenerated {
            queryItems.append(URLQueryItem(name: PageLink.queryAutoName, value: "1"))
        }
        if queryItems.count > 0 {
            urlComponents.queryItems = queryItems
        }
        guard let url = urlComponents.url else {
            preconditionFailure("Failed to create url from components: \(urlComponents)")
        }
        return url
    }

    func withSource(_ source: ModelID? = nil) -> Self {
        return PageLink(destination: self.destination, source: source, autoGenerated: self.autoGenerated)
    }
}
