//
//  V3Plist.swift
//  CoppiceCoreTests
//
//  Created by Martin Pilkington on 01/08/2022.
//

import Foundation
import CoppiceCore
import AppKit

extension TestPlists {
    class V3 {
        let canvasIDs = [UUID(), UUID()]

        lazy var plistCanvases: [[String: Any]] = [
            [
                "id": Canvas.modelID(with: self.canvasIDs[0]).stringRepresentation,
                "title": "Canvas 1",
                "dateCreated": Date(timeIntervalSinceReferenceDate: 30),
                "dateModified": Date(timeIntervalSinceReferenceDate: 300),
                "sortIndex": 2,
                "theme": "auto",
                "viewPort": NSStringFromRect(CGRect(x: 10, y: 20, width: 30, height: 40)),
            ],
            [
                "id": Canvas.modelID(with: self.canvasIDs[1]).stringRepresentation,
                "title": "Canvas 2",
                "dateCreated": Date(timeIntervalSinceReferenceDate: 42),
                "dateModified": Date(timeIntervalSinceReferenceDate: 42),
                "sortIndex": 1,
                "theme": "light",
            ],
        ]

        let pageIDs = [UUID(), UUID(), UUID()]
        lazy var plistPages: [[String: Any]] = [
            [
                "id": Page.modelID(with: self.pageIDs[0]).stringRepresentation,
                "title": "Page 1",
                "dateCreated": Date(timeIntervalSinceReferenceDate: 123),
                "dateModified": Date(timeIntervalSinceReferenceDate: 456),
                "content": ["type": "text", "filename": "\(self.pageIDs[0].uuidString).rtf"],
            ],
            [
                "id": Page.modelID(with: self.pageIDs[1]).stringRepresentation,
                "title": "Page 2",
                "dateCreated": Date(timeIntervalSinceReferenceDate: 0),
                "dateModified": Date(timeIntervalSinceReferenceDate: 0),
                "userPreferredSize": NSStringFromSize(CGSize(width: 1024, height: 768)),
                "content": ["type": "text"],
            ],
            [
                "id": Page.modelID(with: self.pageIDs[2]).stringRepresentation,
                "title": "Page 3",
                "dateCreated": Date(timeIntervalSinceReferenceDate: 999),
                "dateModified": Date(timeIntervalSinceReferenceDate: 9999),
                "content": ["type": "image", "filename": "\(self.pageIDs[2].uuidString).png", "metadata": ["description": "This is an image"]],
            ],
        ]

        let canvasPageIDs = [UUID(), UUID(), UUID(), UUID()]
        lazy var plistCanvasPages: [[String: Any]] = [
            [
                "id": CanvasPage.modelID(with: self.canvasPageIDs[0]).stringRepresentation,
                "frame": NSStringFromRect(CGRect(x: 0, y: 1, width: 2, height: 3)),
                "page": Page.modelID(with: self.pageIDs[0]).stringRepresentation,
                "canvas": Canvas.modelID(with: self.canvasIDs[0]).stringRepresentation,
            ],
            [
                "id": CanvasPage.modelID(with: self.canvasPageIDs[1]).stringRepresentation,
                "frame": NSStringFromRect(CGRect(x: 30, y: 50, width: 200, height: 400)),
                "page": Page.modelID(with: self.pageIDs[1]).stringRepresentation,
                "canvas": Canvas.modelID(with: self.canvasIDs[0]).stringRepresentation,
                "parent": CanvasPage.modelID(with: self.canvasPageIDs[0]).stringRepresentation,
            ],
            [
                "id": CanvasPage.modelID(with: self.canvasPageIDs[2]).stringRepresentation,
                "frame": NSStringFromRect(CGRect(x: -30, y: -2, width: 600, height: 40)),
                "page": Page.modelID(with: self.pageIDs[1]).stringRepresentation,
                "canvas": Canvas.modelID(with: self.canvasIDs[1]).stringRepresentation,
            ],
            [
                "id": CanvasPage.modelID(with: self.canvasPageIDs[3]).stringRepresentation,
                "frame": NSStringFromRect(CGRect(x: 280, y: 50, width: 200, height: 400)),
                "page": Page.modelID(with: self.pageIDs[2]).stringRepresentation,
                "canvas": Canvas.modelID(with: self.canvasIDs[0]).stringRepresentation,
                "parent": CanvasPage.modelID(with: self.canvasPageIDs[1]).stringRepresentation,
            ],
        ]

        
        let canvasLinkIDs = [UUID(), UUID()]
        lazy var plistCanvasLinks: [[String: Any]] = [
            [
                "id": CanvasLink.modelID(with: self.canvasLinkIDs[0]).stringRepresentation,
                "link": PageLink(destination: Page.modelID(with: self.pageIDs[1]), source: Page.modelID(with: self.pageIDs[0]), autoGenerated: false),
                "destinationPage": CanvasPage.modelID(with: self.canvasPageIDs[1]).stringRepresentation,
                "sourcePage": CanvasPage.modelID(with: self.canvasPageIDs[0]).stringRepresentation,
            ],
            [
                "id": CanvasLink.modelID(with: self.canvasLinkIDs[1]).stringRepresentation,
                "link": PageLink(destination: Page.modelID(with: self.pageIDs[2]), source: Page.modelID(with: self.pageIDs[1]), autoGenerated: false),
                "destinationPage": CanvasPage.modelID(with: self.canvasPageIDs[3]).stringRepresentation,
                "sourcePage": CanvasPage.modelID(with: self.canvasPageIDs[1]).stringRepresentation,
            ],
        ]


        let folderIDs = [UUID(), UUID()]
        lazy var plistFolders: [[String: Any]] = [
            [
                "id": Folder.modelID(with: self.folderIDs[0]).stringRepresentation,
                "title": Folder.rootFolderTitle,
                "dateCreated": Date(timeIntervalSinceReferenceDate: 1429),
                "contents": [
                    Page.modelID(with: self.pageIDs[0]).stringRepresentation,
                    Folder.modelID(with: self.folderIDs[1]).stringRepresentation,
                    Page.modelID(with: self.pageIDs[2]).stringRepresentation,
                ],
            ],
            [
                "id": Folder.modelID(with: self.folderIDs[1]).stringRepresentation,
                "title": "My New Folder",
                "dateCreated": Date(timeIntervalSinceReferenceDate: 9241),
                "contents": [
                    Page.modelID(with: self.pageIDs[1]).stringRepresentation,
                ],
            ],
        ]


        lazy var content: [String: Data] = [
            "\(self.pageIDs[0].uuidString).rtf": try! NSAttributedString(string: "Foo Bar").data(from: NSRange(location: 0, length: 7), documentAttributes: [.documentType: NSAttributedString.DocumentType.rtf]),
            "\(self.pageIDs[2].uuidString).png": NSImage(named: "NSAddTemplate")!.pngData()!,
        ]

        var plist: [String: Any] {
            return [
                "canvases": self.plistCanvases,
                "pages": self.plistPages,
                "canvasPages": self.plistCanvasPages,
                "folders": self.plistFolders,
                "canvasLinks": self.plistCanvasLinks,
                "version": 3,
            ]
        }
    }
}
