//
//  PageLink.swift
//  Coppice
//
//  Created by Martin Pilkington on 28/10/2019.
//  Copyright © 2019 M Cubed Software. All rights reserved.
//

import Cocoa
import M3Data

public struct PageLink: Equatable, Hashable {
    public static let host = "page"
    public static let querySourceName = "source"
    public static let queryAutoName = "auto"
    public let destination: ModelID
    public let source: ModelID?
    public let autoGenerated: Bool

    public init(destinationPage: Page, sourceCanvasPage: CanvasPage? = nil, autoGenerated: Bool = false) {
        self.init(destination: destinationPage.id, source: sourceCanvasPage?.id, autoGenerated: autoGenerated)
    }

    public init(destination: ModelID, source: ModelID? = nil, autoGenerated: Bool = false) {
        self.destination = destination
        self.source = source
        self.autoGenerated = autoGenerated
    }

    public init?(url: URL) {
        guard let urlComponents = URLComponents(url: url, resolvingAgainstBaseURL: false),
            urlComponents.scheme == GlobalConstants.urlScheme,
            urlComponents.host == PageLink.host
        else {
            return nil
        }

        let path = urlComponents.path
        let destinationUUIDString = String(path[(path.index(after: path.startIndex))...])
        guard let destinationID = Page.modelID(withUUIDString: destinationUUIDString) else {
            return nil
        }

        var sourceID: ModelID? = nil
        var autoGenerated = false
        if let queryItems = urlComponents.queryItems?.indexed(by: \.name) {
            if let value = queryItems[PageLink.querySourceName]?.value {
                sourceID = CanvasPage.modelID(withUUIDString: value)
            }
            if let value = queryItems[PageLink.queryAutoName]?.value {
                autoGenerated = (value == "1")
            }
        }

        self.init(destination: destinationID, source: sourceID, autoGenerated: autoGenerated)
    }

    public var url: URL {
        var urlComponents = URLComponents()
        urlComponents.scheme = GlobalConstants.urlScheme
        urlComponents.host = PageLink.host
        urlComponents.path = "/\(self.destination.uuid.uuidString)"
        var queryItems = [URLQueryItem]()
        if let source = self.source {
            queryItems.append(URLQueryItem(name: PageLink.querySourceName, value: source.uuid.uuidString))
        }
        if self.autoGenerated {
            queryItems.append(URLQueryItem(name: PageLink.queryAutoName, value: "1"))
        }
        if queryItems.count > 0 {
            urlComponents.queryItems = queryItems
        }
        guard let url = urlComponents.url else {
            preconditionFailure("Failed to create url from components: \(urlComponents)")
        }
        return url
    }

    public func withSource(_ source: ModelID? = nil) -> Self {
        return PageLink(destination: self.destination, source: source, autoGenerated: self.autoGenerated)
    }

    public static func == (lhs: PageLink, rhs: PageLink) -> Bool {
        return lhs.destination == rhs.destination && lhs.source == rhs.source
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.destination)
        hasher.combine(self.source)
    }
}
